version: '3.8'

services:
  db_service:
    image: mysql:8.0
    container_name: my_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Sesuaikan dengan password di .env
      MYSQL_DATABASE: db_gearhike
    volumes:
      - db_data:/var/lib/mysql
      # Pastikan folder database berisi file init.sql milikmu
      - ./database:/docker-entrypoint-initdb.d 
    networks:
      - app_network

  backend_app:
    build: ./app
    container_name: my_backend
    restart: always
    # Port 3000 tetap dibuka untuk internal/testing jika perlu
    expose:
      - "3000"
    depends_on:
      - db_service
    environment:
      DB_HOST: db_service
      DB_NAME: db_gearhike
      DB_USER: root
      DB_PASS: rootpassword
    networks:
      - app_network

  nginx_proxy:
    image: nginx:alpine
    container_name: my_nginx
    restart: always
    ports:
      - "2583:80" # PERUBAHAN: Sekarang diakses lewat port 2583
    volumes:
      # Menggunakan path default nginx yang umum
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend_app
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
